/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param body 
 * @param norm 
 * @param standard 
 * @param version 
 */
@JsonClass(generateAdapter = true)
data class CompliancesCompliance (

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "norm")
    val norm: kotlin.String? = null,

    @Json(name = "standard")
    val standard: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.String? = null

)

