/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CompliancesCompliance

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param safety List of safety standards the device is compliant with.
 * @param radioEquipment List of radio equipment standards the device is compliant with.
 */
@JsonClass(generateAdapter = true)
data class EndDeviceModelCompliances (

    /* List of safety standards the device is compliant with. */
    @Json(name = "safety")
    val safety: kotlin.collections.List<CompliancesCompliance>? = null,

    /* List of radio equipment standards the device is compliant with. */
    @Json(name = "radio_equipment")
    val radioEquipment: kotlin.collections.List<CompliancesCompliance>? = null

)

