/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param width Device width (mm).
 * @param height Device height (mm).
 * @param diameter Device diameter (mm).
 * @param length Device length (mm).
 */
@JsonClass(generateAdapter = true)
data class EndDeviceModelDimensions (

    /* Device width (mm). */
    @Json(name = "width")
    val width: kotlin.Float? = null,

    /* Device height (mm). */
    @Json(name = "height")
    val height: kotlin.Float? = null,

    /* Device diameter (mm). */
    @Json(name = "diameter")
    val diameter: kotlin.Float? = null,

    /* Device length (mm). */
    @Json(name = "length")
    val length: kotlin.Float? = null

)

