/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FirmwareVersionProfile

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param version Firmware version string.
 * @param numeric Numeric firmware revision number.
 * @param supportedHardwareVersions Hardware versions supported by this firmware version.
 * @param profiles Device profiles for each supported region (band).
 */
@JsonClass(generateAdapter = true)
data class EndDeviceModelFirmwareVersion (

    /* Firmware version string. */
    @Json(name = "version")
    val version: kotlin.String? = null,

    /* Numeric firmware revision number. */
    @Json(name = "numeric")
    val numeric: kotlin.Long? = null,

    /* Hardware versions supported by this firmware version. */
    @Json(name = "supported_hardware_versions")
    val supportedHardwareVersions: kotlin.collections.List<kotlin.String>? = null,

    /* Device profiles for each supported region (band). */
    @Json(name = "profiles")
    val profiles: kotlin.collections.Map<kotlin.String, FirmwareVersionProfile>? = null

)

