/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type The type of authentication that was used. This is typically a bearer token.
 * @param tokenType The type of token that was used. Common types are APIKey, AccessToken and SessionToken.
 * @param tokenId The ID of the token that was used.
 */
@JsonClass(generateAdapter = true)
data class EventAuthentication (

    /* The type of authentication that was used. This is typically a bearer token. */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* The type of token that was used. Common types are APIKey, AccessToken and SessionToken. */
    @Json(name = "token_type")
    val tokenType: kotlin.String? = null,

    /* The ID of the token that was used. */
    @Json(name = "token_id")
    val tokenId: kotlin.String? = null

)

