/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3UserIdentifiers

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email 
 * @param token 
 * @param expiresAt 
 * @param createdAt 
 * @param updatedAt 
 * @param acceptedAt 
 * @param acceptedBy 
 */
@JsonClass(generateAdapter = true)
data class Lorawanv3Invitation (

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "token")
    val token: kotlin.String? = null,

    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "accepted_at")
    val acceptedAt: java.time.OffsetDateTime? = null,

    @Json(name = "accepted_by")
    val acceptedBy: V3UserIdentifiers? = null

)

