/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3DataRateIndex

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dataRateIndex 
 * @param txPowerIndex 
 * @param channelMask 
 * @param channelMaskControl 
 * @param nbTrans 
 */
@JsonClass(generateAdapter = true)
data class MACCommandLinkADRReq (

    @Json(name = "data_rate_index")
    val dataRateIndex: V3DataRateIndex? = V3DataRateIndex._0,

    @Json(name = "tx_power_index")
    val txPowerIndex: kotlin.Long? = null,

    @Json(name = "channel_mask")
    val channelMask: kotlin.collections.List<kotlin.Boolean>? = null,

    @Json(name = "channel_mask_control")
    val channelMaskControl: kotlin.Long? = null,

    @Json(name = "nb_trans")
    val nbTrans: kotlin.Long? = null

)

