/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param frequencyAck 
 * @param dataRateAck 
 */
@JsonClass(generateAdapter = true)
data class MACCommandNewChannelAns (

    @Json(name = "frequency_ack")
    val frequencyAck: kotlin.Boolean? = null,

    @Json(name = "data_rate_ack")
    val dataRateAck: kotlin.Boolean? = null

)

