/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param minLength 
 * @param maxLength 
 * @param minUppercase 
 * @param minDigits 
 * @param minSpecial 
 */
@JsonClass(generateAdapter = true)
data class UserRegistrationPasswordRequirements (

    @Json(name = "min_length")
    val minLength: kotlin.Long? = null,

    @Json(name = "max_length")
    val maxLength: kotlin.Long? = null,

    @Json(name = "min_uppercase")
    val minUppercase: kotlin.Long? = null,

    @Json(name = "min_digits")
    val minDigits: kotlin.Long? = null,

    @Json(name = "min_special")
    val minSpecial: kotlin.Long? = null

)

