/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3KeyEnvelope

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kekLabel The KEK label to use for wrapping application keys.
 * @param kek 
 * @param homeNetId Home NetID.
 * @param applicationServerId The AS-ID of the Application Server to use.
 */
@JsonClass(generateAdapter = true)
data class V3ApplicationActivationSettings (

    /* The KEK label to use for wrapping application keys. */
    @Json(name = "kek_label")
    val kekLabel: kotlin.String? = null,

    @Json(name = "kek")
    val kek: V3KeyEnvelope? = null,

    /* Home NetID. */
    @Json(name = "home_net_id")
    val homeNetId: kotlin.ByteArray? = null,

    /* The AS-ID of the Application Server to use. */
    @Json(name = "application_server_id")
    val applicationServerId: kotlin.String? = null

)

