/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ApplicationDownlinkClassBC
import org.openapitools.client.models.V3TxSchedulePriority

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sessionKeyId Join Server issued identifier for the session keys used by this downlink.
 * @param fPort 
 * @param fCnt 
 * @param frmPayload The frame payload of the downlink message. The payload is encrypted if the skip_payload_crypto field of the EndDevice is true.
 * @param decodedPayload The decoded frame payload of the downlink message. When scheduling downlink with a message processor configured for the end device (see formatters) or application (see default_formatters), this fields acts as input for the downlink encoder, and the output is set to frm_payload. When reading downlink (listing the queue, downlink message events, etc), this fields acts as output of the downlink decoder, and the input is frm_payload.
 * @param decodedPayloadWarnings Warnings generated by the message processor while encoding frm_payload (scheduling downlink) or decoding the frm_payload (reading downlink).
 * @param confirmed 
 * @param classBC 
 * @param priority 
 * @param correlationIds 
 */
@JsonClass(generateAdapter = true)
data class V3ApplicationDownlink (

    /* Join Server issued identifier for the session keys used by this downlink. */
    @Json(name = "session_key_id")
    val sessionKeyId: kotlin.ByteArray? = null,

    @Json(name = "f_port")
    val fPort: kotlin.Long? = null,

    @Json(name = "f_cnt")
    val fCnt: kotlin.Long? = null,

    /* The frame payload of the downlink message. The payload is encrypted if the skip_payload_crypto field of the EndDevice is true. */
    @Json(name = "frm_payload")
    val frmPayload: kotlin.ByteArray? = null,

    /* The decoded frame payload of the downlink message. When scheduling downlink with a message processor configured for the end device (see formatters) or application (see default_formatters), this fields acts as input for the downlink encoder, and the output is set to frm_payload. When reading downlink (listing the queue, downlink message events, etc), this fields acts as output of the downlink decoder, and the input is frm_payload. */
    @Json(name = "decoded_payload")
    val decodedPayload: kotlin.Any? = null,

    /* Warnings generated by the message processor while encoding frm_payload (scheduling downlink) or decoding the frm_payload (reading downlink). */
    @Json(name = "decoded_payload_warnings")
    val decodedPayloadWarnings: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "confirmed")
    val confirmed: kotlin.Boolean? = null,

    @Json(name = "class_b_c")
    val classBC: ApplicationDownlinkClassBC? = null,

    @Json(name = "priority")
    val priority: V3TxSchedulePriority? = V3TxSchedulePriority.lOWEST,

    @Json(name = "correlation_ids")
    val correlationIds: kotlin.collections.List<kotlin.String>? = null

)

