/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3ApplicationIdentifiers
import org.openapitools.client.models.V3ContactInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Application is the message that defines an Application in the network.
 *
 * @param ids 
 * @param createdAt When the application was created. This information is public and can be seen by any authenticated user in the network.
 * @param updatedAt When the application was last updated. This information is public and can be seen by any authenticated user in the network.
 * @param deletedAt When the application was deleted. This information is public and can be seen by any authenticated user in the network.
 * @param name The name of the application.
 * @param description A description for the application.
 * @param attributes Key-value attributes for this application. Typically used for organizing applications or for storing integration-specific data.
 * @param contactInfo Contact information for this application. Typically used to indicate who to contact with technical/security questions about the application.
 * @param devEuiCounter 
 */
@JsonClass(generateAdapter = true)
data class V3Application (

    @Json(name = "ids")
    val ids: V3ApplicationIdentifiers? = null,

    /* When the application was created. This information is public and can be seen by any authenticated user in the network. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    /* When the application was last updated. This information is public and can be seen by any authenticated user in the network. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,

    /* When the application was deleted. This information is public and can be seen by any authenticated user in the network. */
    @Json(name = "deleted_at")
    val deletedAt: java.time.OffsetDateTime? = null,

    /* The name of the application. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* A description for the application. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Key-value attributes for this application. Typically used for organizing applications or for storing integration-specific data. */
    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Contact information for this application. Typically used to indicate who to contact with technical/security questions about the application. */
    @Json(name = "contact_info")
    val contactInfo: kotlin.collections.List<V3ContactInfo>? = null,

    @Json(name = "dev_eui_counter")
    val devEuiCounter: kotlin.Long? = null

)

