/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3Right

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Immutable and unique public identifier for the API key. Generated by the Access Server.
 * @param key Immutable and unique secret value of the API key. Generated by the Access Server.
 * @param name User-defined (friendly) name for the API key.
 * @param rights Rights that are granted to this API key.
 * @param createdAt 
 * @param updatedAt 
 * @param expiresAt 
 */
@JsonClass(generateAdapter = true)
data class V3APIKey (

    /* Immutable and unique public identifier for the API key. Generated by the Access Server. */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Immutable and unique secret value of the API key. Generated by the Access Server. */
    @Json(name = "key")
    val key: kotlin.String? = null,

    /* User-defined (friendly) name for the API key. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Rights that are granted to this API key. */
    @Json(name = "rights")
    val rights: kotlin.collections.List<V3Right>? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "expires_at")
    val expiresAt: java.time.OffsetDateTime? = null

)

