/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuthInfoResponseAPIKeyAccess
import org.openapitools.client.models.V3OAuthAccessToken
import org.openapitools.client.models.V3Rights
import org.openapitools.client.models.V3UserSession

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param apiKey 
 * @param oauthAccessToken 
 * @param userSession 
 * @param universalRights 
 * @param isAdmin 
 */
@JsonClass(generateAdapter = true)
data class V3AuthInfoResponse (

    @Json(name = "api_key")
    val apiKey: AuthInfoResponseAPIKeyAccess? = null,

    @Json(name = "oauth_access_token")
    val oauthAccessToken: V3OAuthAccessToken? = null,

    @Json(name = "user_session")
    val userSession: V3UserSession? = null,

    @Json(name = "universal_rights")
    val universalRights: V3Rights? = null,

    @Json(name = "is_admin")
    val isAdmin: kotlin.Boolean? = null

)

