/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: oTHER,aBUSE,bILLING,tECHNICAL
 */

enum class V3ContactType(val value: kotlin.String) {

    @Json(name = "CONTACT_TYPE_OTHER")
    oTHER("CONTACT_TYPE_OTHER"),

    @Json(name = "CONTACT_TYPE_ABUSE")
    aBUSE("CONTACT_TYPE_ABUSE"),

    @Json(name = "CONTACT_TYPE_BILLING")
    bILLING("CONTACT_TYPE_BILLING"),

    @Json(name = "CONTACT_TYPE_TECHNICAL")
    tECHNICAL("CONTACT_TYPE_TECHNICAL");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V3ContactType) "$data" else null

        /**
         * Returns a valid [V3ContactType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V3ContactType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

