/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CUPSRedirectionClientTLS

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param targetCupsUri CUPS URI for LoRa Basics Station CUPS redirection.
 * @param currentGatewayKey The key set in the gateway to authenticate itself.
 * @param targetCupsTrust Optional PEM encoded CA Root certificate. If this field is empty, DCS will attempt to dial the Target CUPS server and fetch the CA.
 * @param clientTls 
 * @param authToken The Device Claiming Server will fill this field with a The Things Stack API Key.
 */
@JsonClass(generateAdapter = true)
data class V3CUPSRedirection (

    /* CUPS URI for LoRa Basics Station CUPS redirection. */
    @Json(name = "target_cups_uri")
    val targetCupsUri: kotlin.String? = null,

    /* The key set in the gateway to authenticate itself. */
    @Json(name = "current_gateway_key")
    val currentGatewayKey: kotlin.String? = null,

    /* Optional PEM encoded CA Root certificate. If this field is empty, DCS will attempt to dial the Target CUPS server and fetch the CA. */
    @Json(name = "target_cups_trust")
    val targetCupsTrust: kotlin.ByteArray? = null,

    @Json(name = "client_tls")
    val clientTls: CUPSRedirectionClientTLS? = null,

    /* The Device Claiming Server will fill this field with a The Things Stack API Key. */
    @Json(name = "auth_token")
    val authToken: kotlin.String? = null

)

