/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *  - DOWNLINK_PATH_CONSTRAINT_NONE: Indicates that the gateway can be selected for downlink without constraints by the Network Server.  - DOWNLINK_PATH_CONSTRAINT_PREFER_OTHER: Indicates that the gateway can be selected for downlink only if no other or better gateway can be selected.  - DOWNLINK_PATH_CONSTRAINT_NEVER: Indicates that this gateway will never be selected for downlink, even if that results in no available downlink path.
 *
 * Values: nONE,pREFEROTHER,nEVER
 */

enum class V3DownlinkPathConstraint(val value: kotlin.String) {

    @Json(name = "DOWNLINK_PATH_CONSTRAINT_NONE")
    nONE("DOWNLINK_PATH_CONSTRAINT_NONE"),

    @Json(name = "DOWNLINK_PATH_CONSTRAINT_PREFER_OTHER")
    pREFEROTHER("DOWNLINK_PATH_CONSTRAINT_PREFER_OTHER"),

    @Json(name = "DOWNLINK_PATH_CONSTRAINT_NEVER")
    nEVER("DOWNLINK_PATH_CONSTRAINT_NEVER");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V3DownlinkPathConstraint) "$data" else null

        /**
         * Returns a valid [V3DownlinkPathConstraint] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V3DownlinkPathConstraint? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

