/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param brandId Brand identifier, as specified in the Device Repository.
 * @param name Brand name.
 * @param privateEnterpriseNumber Private Enterprise Number (PEN) assigned by IANA.
 * @param organizationUniqueIdentifiers Organization Unique Identifiers (OUI) assigned by IEEE.
 * @param loraAllianceVendorId VendorID managed by the LoRa Alliance, as defined in TR005.
 * @param website Brand website URL.
 * @param email Contact email address.
 * @param logo Path to brand logo.
 */
@JsonClass(generateAdapter = true)
data class V3EndDeviceBrand (

    /* Brand identifier, as specified in the Device Repository. */
    @Json(name = "brand_id")
    val brandId: kotlin.String? = null,

    /* Brand name. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Private Enterprise Number (PEN) assigned by IANA. */
    @Json(name = "private_enterprise_number")
    val privateEnterpriseNumber: kotlin.Long? = null,

    /* Organization Unique Identifiers (OUI) assigned by IEEE. */
    @Json(name = "organization_unique_identifiers")
    val organizationUniqueIdentifiers: kotlin.collections.List<kotlin.String>? = null,

    /* VendorID managed by the LoRa Alliance, as defined in TR005. */
    @Json(name = "lora_alliance_vendor_id")
    val loraAllianceVendorId: kotlin.Long? = null,

    /* Brand website URL. */
    @Json(name = "website")
    val website: kotlin.String? = null,

    /* Contact email address. */
    @Json(name = "email")
    val email: kotlin.String? = null,

    /* Path to brand logo. */
    @Json(name = "logo")
    val logo: kotlin.String? = null

)

