/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3FCtrl

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param devAddr 
 * @param fCtrl 
 * @param fCnt 
 * @param fOpts 
 */
@JsonClass(generateAdapter = true)
data class V3FHDR (

    @Json(name = "dev_addr")
    val devAddr: kotlin.ByteArray? = null,

    @Json(name = "f_ctrl")
    val fCtrl: V3FCtrl? = null,

    @Json(name = "f_cnt")
    val fCnt: kotlin.Long? = null,

    @Json(name = "f_opts")
    val fOpts: kotlin.ByteArray? = null

)

