/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Lorawanv3Location
import org.openapitools.client.models.V3GatewayAntennaPlacement

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * GatewayAntenna is the message that defines a gateway antenna.
 *
 * @param gain Antenna gain relative to the gateway, in dBi.
 * @param location 
 * @param attributes 
 * @param placement 
 */
@JsonClass(generateAdapter = true)
data class V3GatewayAntenna (

    /* Antenna gain relative to the gateway, in dBi. */
    @Json(name = "gain")
    val gain: kotlin.Float? = null,

    @Json(name = "location")
    val location: Lorawanv3Location? = null,

    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "placement")
    val placement: V3GatewayAntennaPlacement? = V3GatewayAntennaPlacement.pLACEMENTUNKNOWN

)

