/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3SessionKeys

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param rawPayload 
 * @param sessionKeys 
 * @param lifetime 
 * @param correlationIds 
 */
@JsonClass(generateAdapter = true)
data class V3JoinResponse (

    @Json(name = "raw_payload")
    val rawPayload: kotlin.ByteArray? = null,

    @Json(name = "session_keys")
    val sessionKeys: V3SessionKeys? = null,

    @Json(name = "lifetime")
    val lifetime: kotlin.String? = null,

    @Json(name = "correlation_ids")
    val correlationIds: kotlin.collections.List<kotlin.String>? = null

)

