/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *  - KEY_PROVISIONING_UNKNOWN: Unknown Key Provisioning.  - KEY_PROVISIONING_CUSTOM: Custom Key Provisioning.  - KEY_PROVISIONING_JOIN_SERVER: Key Provisioning from the Global Join Server.  - KEY_PROVISIONING_MANIFEST: Key Provisioning from Manifest.
 *
 * Values: uNKNOWN,cUSTOM,jOINSERVER,mANIFEST
 */

enum class V3KeyProvisioning(val value: kotlin.String) {

    @Json(name = "KEY_PROVISIONING_UNKNOWN")
    uNKNOWN("KEY_PROVISIONING_UNKNOWN"),

    @Json(name = "KEY_PROVISIONING_CUSTOM")
    cUSTOM("KEY_PROVISIONING_CUSTOM"),

    @Json(name = "KEY_PROVISIONING_JOIN_SERVER")
    jOINSERVER("KEY_PROVISIONING_JOIN_SERVER"),

    @Json(name = "KEY_PROVISIONING_MANIFEST")
    mANIFEST("KEY_PROVISIONING_MANIFEST");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V3KeyProvisioning) "$data" else null

        /**
         * Returns a valid [V3KeyProvisioning] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V3KeyProvisioning? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

