/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Lorawanv3BoolValue
import org.openapitools.client.models.V3ADRAckDelayExponentValue
import org.openapitools.client.models.V3ADRAckLimitExponentValue
import org.openapitools.client.models.V3AggregatedDutyCycleValue
import org.openapitools.client.models.V3DataRateIndexValue
import org.openapitools.client.models.V3DataRateOffsetValue
import org.openapitools.client.models.V3DeviceEIRPValue
import org.openapitools.client.models.V3FrequencyValue
import org.openapitools.client.models.V3PingSlotPeriodValue
import org.openapitools.client.models.V3RxDelayValue

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param classBTimeout Maximum delay for the device to answer a MAC request or a confirmed downlink frame. If unset, the default value from Network Server configuration will be used.
 * @param pingSlotPeriodicity 
 * @param pingSlotDataRateIndex 
 * @param pingSlotFrequency 
 * @param beaconFrequency 
 * @param classCTimeout Maximum delay for the device to answer a MAC request or a confirmed downlink frame. If unset, the default value from Network Server configuration will be used.
 * @param rx1Delay 
 * @param rx1DataRateOffset 
 * @param rx2DataRateIndex 
 * @param rx2Frequency 
 * @param factoryPresetFrequencies List of factory-preset frequencies. If unset, the default value from Network Server configuration or regional parameters specification will be used.
 * @param maxDutyCycle 
 * @param supports32BitFCnt 
 * @param useAdr 
 * @param adrMargin The ADR margin tells the network server how much margin it should add in ADR requests. A bigger margin is less efficient, but gives a better chance of successful reception. If unset, the default value from Network Server configuration will be used.
 * @param resetsFCnt 
 * @param statusTimePeriodicity The interval after which a DevStatusReq MACCommand shall be sent. If unset, the default value from Network Server configuration will be used.
 * @param statusCountPeriodicity Number of uplink messages after which a DevStatusReq MACCommand shall be sent. If unset, the default value from Network Server configuration will be used.
 * @param desiredRx1Delay 
 * @param desiredRx1DataRateOffset 
 * @param desiredRx2DataRateIndex 
 * @param desiredRx2Frequency 
 * @param desiredMaxDutyCycle 
 * @param desiredAdrAckLimitExponent 
 * @param desiredAdrAckDelayExponent 
 * @param desiredPingSlotDataRateIndex 
 * @param desiredPingSlotFrequency 
 * @param desiredBeaconFrequency 
 * @param desiredMaxEirp 
 * @param classBCDownlinkInterval The minimum duration passed before a network-initiated(e.g. Class B or C) downlink following an arbitrary downlink.
 */
@JsonClass(generateAdapter = true)
data class V3MACSettings (

    /* Maximum delay for the device to answer a MAC request or a confirmed downlink frame. If unset, the default value from Network Server configuration will be used. */
    @Json(name = "class_b_timeout")
    val classBTimeout: kotlin.String? = null,

    @Json(name = "ping_slot_periodicity")
    val pingSlotPeriodicity: V3PingSlotPeriodValue? = null,

    @Json(name = "ping_slot_data_rate_index")
    val pingSlotDataRateIndex: V3DataRateIndexValue? = null,

    @Json(name = "ping_slot_frequency")
    val pingSlotFrequency: V3FrequencyValue? = null,

    @Json(name = "beacon_frequency")
    val beaconFrequency: V3FrequencyValue? = null,

    /* Maximum delay for the device to answer a MAC request or a confirmed downlink frame. If unset, the default value from Network Server configuration will be used. */
    @Json(name = "class_c_timeout")
    val classCTimeout: kotlin.String? = null,

    @Json(name = "rx1_delay")
    val rx1Delay: V3RxDelayValue? = null,

    @Json(name = "rx1_data_rate_offset")
    val rx1DataRateOffset: V3DataRateOffsetValue? = null,

    @Json(name = "rx2_data_rate_index")
    val rx2DataRateIndex: V3DataRateIndexValue? = null,

    @Json(name = "rx2_frequency")
    val rx2Frequency: V3FrequencyValue? = null,

    /* List of factory-preset frequencies. If unset, the default value from Network Server configuration or regional parameters specification will be used. */
    @Json(name = "factory_preset_frequencies")
    val factoryPresetFrequencies: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "max_duty_cycle")
    val maxDutyCycle: V3AggregatedDutyCycleValue? = null,

    @Json(name = "supports_32_bit_f_cnt")
    val supports32BitFCnt: Lorawanv3BoolValue? = null,

    @Json(name = "use_adr")
    val useAdr: Lorawanv3BoolValue? = null,

    /* The ADR margin tells the network server how much margin it should add in ADR requests. A bigger margin is less efficient, but gives a better chance of successful reception. If unset, the default value from Network Server configuration will be used. */
    @Json(name = "adr_margin")
    val adrMargin: kotlin.Float? = null,

    @Json(name = "resets_f_cnt")
    val resetsFCnt: Lorawanv3BoolValue? = null,

    /* The interval after which a DevStatusReq MACCommand shall be sent. If unset, the default value from Network Server configuration will be used. */
    @Json(name = "status_time_periodicity")
    val statusTimePeriodicity: kotlin.String? = null,

    /* Number of uplink messages after which a DevStatusReq MACCommand shall be sent. If unset, the default value from Network Server configuration will be used. */
    @Json(name = "status_count_periodicity")
    val statusCountPeriodicity: kotlin.Long? = null,

    @Json(name = "desired_rx1_delay")
    val desiredRx1Delay: V3RxDelayValue? = null,

    @Json(name = "desired_rx1_data_rate_offset")
    val desiredRx1DataRateOffset: V3DataRateOffsetValue? = null,

    @Json(name = "desired_rx2_data_rate_index")
    val desiredRx2DataRateIndex: V3DataRateIndexValue? = null,

    @Json(name = "desired_rx2_frequency")
    val desiredRx2Frequency: V3FrequencyValue? = null,

    @Json(name = "desired_max_duty_cycle")
    val desiredMaxDutyCycle: V3AggregatedDutyCycleValue? = null,

    @Json(name = "desired_adr_ack_limit_exponent")
    val desiredAdrAckLimitExponent: V3ADRAckLimitExponentValue? = null,

    @Json(name = "desired_adr_ack_delay_exponent")
    val desiredAdrAckDelayExponent: V3ADRAckDelayExponentValue? = null,

    @Json(name = "desired_ping_slot_data_rate_index")
    val desiredPingSlotDataRateIndex: V3DataRateIndexValue? = null,

    @Json(name = "desired_ping_slot_frequency")
    val desiredPingSlotFrequency: V3FrequencyValue? = null,

    @Json(name = "desired_beacon_frequency")
    val desiredBeaconFrequency: V3FrequencyValue? = null,

    @Json(name = "desired_max_eirp")
    val desiredMaxEirp: V3DeviceEIRPValue? = null,

    /* The minimum duration passed before a network-initiated(e.g. Class B or C) downlink following an arbitrary downlink. */
    @Json(name = "class_b_c_downlink_interval")
    val classBCDownlinkInterval: kotlin.String? = null

)

