/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: uNKNOWN,v10,v101,v102,v11,v103,v104
 */

enum class V3MACVersion(val value: kotlin.String) {

    @Json(name = "MAC_UNKNOWN")
    uNKNOWN("MAC_UNKNOWN"),

    @Json(name = "MAC_V1_0")
    v10("MAC_V1_0"),

    @Json(name = "MAC_V1_0_1")
    v101("MAC_V1_0_1"),

    @Json(name = "MAC_V1_0_2")
    v102("MAC_V1_0_2"),

    @Json(name = "MAC_V1_1")
    v11("MAC_V1_1"),

    @Json(name = "MAC_V1_0_3")
    v103("MAC_V1_0_3"),

    @Json(name = "MAC_V1_0_4")
    v104("MAC_V1_0_4");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V3MACVersion) "$data" else null

        /**
         * Returns a valid [V3MACVersion] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V3MACVersion? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

