/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param location Show location.
 * @param antennaPlacement Show antenna placement (indoor/outdoor).
 * @param antennaCount Show antenna count.
 * @param fineTimestamps Show whether the gateway produces fine timestamps.
 * @param contactInfo Show contact information.
 * @param status Show status (online/offline).
 * @param frequencyPlan Show frequency plan.
 * @param packetRates Show receive and transmission packet rates.
 */
@JsonClass(generateAdapter = true)
data class V3PacketBrokerGatewayVisibility (

    /* Show location. */
    @Json(name = "location")
    val location: kotlin.Boolean? = null,

    /* Show antenna placement (indoor/outdoor). */
    @Json(name = "antenna_placement")
    val antennaPlacement: kotlin.Boolean? = null,

    /* Show antenna count. */
    @Json(name = "antenna_count")
    val antennaCount: kotlin.Boolean? = null,

    /* Show whether the gateway produces fine timestamps. */
    @Json(name = "fine_timestamps")
    val fineTimestamps: kotlin.Boolean? = null,

    /* Show contact information. */
    @Json(name = "contact_info")
    val contactInfo: kotlin.Boolean? = null,

    /* Show status (online/offline). */
    @Json(name = "status")
    val status: kotlin.Boolean? = null,

    /* Show frequency plan. */
    @Json(name = "frequency_plan")
    val frequencyPlan: kotlin.Boolean? = null,

    /* Show receive and transmission packet rates. */
    @Json(name = "packet_rates")
    val packetRates: kotlin.Boolean? = null

)

