/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3PacketBrokerGatewayVisibility

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param updatedAt Timestamp when the policy got last updated.
 * @param visibility 
 */
@JsonClass(generateAdapter = true)
data class V3PacketBrokerDefaultGatewayVisibility (

    /* Timestamp when the policy got last updated. */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "visibility")
    val visibility: V3PacketBrokerGatewayVisibility? = null

)

