/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param joinAccept Allow join-accept messages.
 * @param macData Allow downlink messages with FPort of 0.
 * @param applicationData Allow downlink messages with FPort between 1 and 255.
 */
@JsonClass(generateAdapter = true)
data class V3PacketBrokerRoutingPolicyDownlink (

    /* Allow join-accept messages. */
    @Json(name = "join_accept")
    val joinAccept: kotlin.Boolean? = null,

    /* Allow downlink messages with FPort of 0. */
    @Json(name = "mac_data")
    val macData: kotlin.Boolean? = null,

    /* Allow downlink messages with FPort between 1 and 255. */
    @Json(name = "application_data")
    val applicationData: kotlin.Boolean? = null

)

