/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PictureEmbedded

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param embedded 
 * @param sizes URLs of the picture for different sizes, if available on a CDN.
 */
@JsonClass(generateAdapter = true)
data class V3Picture (

    @Json(name = "embedded")
    val embedded: PictureEmbedded? = null,

    /* URLs of the picture for different sizes, if available on a CDN. */
    @Json(name = "sizes")
    val sizes: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

)

