/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3QRCodeFormat

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param formats Available formats. The map key is the format identifier.
 */
@JsonClass(generateAdapter = true)
data class V3QRCodeFormats (

    /* Available formats. The map key is the format identifier. */
    @Json(name = "formats")
    val formats: kotlin.collections.Map<kotlin.String, V3QRCodeFormat>? = null

)

