/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: _0,_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15
 */

enum class V3RejoinTimeExponent(val value: kotlin.String) {

    @Json(name = "REJOIN_TIME_0")
    _0("REJOIN_TIME_0"),

    @Json(name = "REJOIN_TIME_1")
    _1("REJOIN_TIME_1"),

    @Json(name = "REJOIN_TIME_2")
    _2("REJOIN_TIME_2"),

    @Json(name = "REJOIN_TIME_3")
    _3("REJOIN_TIME_3"),

    @Json(name = "REJOIN_TIME_4")
    _4("REJOIN_TIME_4"),

    @Json(name = "REJOIN_TIME_5")
    _5("REJOIN_TIME_5"),

    @Json(name = "REJOIN_TIME_6")
    _6("REJOIN_TIME_6"),

    @Json(name = "REJOIN_TIME_7")
    _7("REJOIN_TIME_7"),

    @Json(name = "REJOIN_TIME_8")
    _8("REJOIN_TIME_8"),

    @Json(name = "REJOIN_TIME_9")
    _9("REJOIN_TIME_9"),

    @Json(name = "REJOIN_TIME_10")
    _10("REJOIN_TIME_10"),

    @Json(name = "REJOIN_TIME_11")
    _11("REJOIN_TIME_11"),

    @Json(name = "REJOIN_TIME_12")
    _12("REJOIN_TIME_12"),

    @Json(name = "REJOIN_TIME_13")
    _13("REJOIN_TIME_13"),

    @Json(name = "REJOIN_TIME_14")
    _14("REJOIN_TIME_14"),

    @Json(name = "REJOIN_TIME_15")
    _15("REJOIN_TIME_15");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V3RejoinTimeExponent) "$data" else null

        /**
         * Returns a valid [V3RejoinTimeExponent] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V3RejoinTimeExponent? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

