/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: _0,_1,_2,_3,_4,_5,_6,_7
 */

enum class V3RejoinPeriodExponent(val value: kotlin.String) {

    @Json(name = "REJOIN_PERIOD_0")
    _0("REJOIN_PERIOD_0"),

    @Json(name = "REJOIN_PERIOD_1")
    _1("REJOIN_PERIOD_1"),

    @Json(name = "REJOIN_PERIOD_2")
    _2("REJOIN_PERIOD_2"),

    @Json(name = "REJOIN_PERIOD_3")
    _3("REJOIN_PERIOD_3"),

    @Json(name = "REJOIN_PERIOD_4")
    _4("REJOIN_PERIOD_4"),

    @Json(name = "REJOIN_PERIOD_5")
    _5("REJOIN_PERIOD_5"),

    @Json(name = "REJOIN_PERIOD_6")
    _6("REJOIN_PERIOD_6"),

    @Json(name = "REJOIN_PERIOD_7")
    _7("REJOIN_PERIOD_7");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V3RejoinPeriodExponent) "$data" else null

        /**
         * Returns a valid [V3RejoinPeriodExponent] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V3RejoinPeriodExponent? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

