/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: lOWEST,lOW,bELOWNORMAL,nORMAL,aBOVENORMAL,hIGH,hIGHEST
 */

enum class V3TxSchedulePriority(val value: kotlin.String) {

    @Json(name = "LOWEST")
    lOWEST("LOWEST"),

    @Json(name = "LOW")
    lOW("LOW"),

    @Json(name = "BELOW_NORMAL")
    bELOWNORMAL("BELOW_NORMAL"),

    @Json(name = "NORMAL")
    nORMAL("NORMAL"),

    @Json(name = "ABOVE_NORMAL")
    aBOVENORMAL("ABOVE_NORMAL"),

    @Json(name = "HIGH")
    hIGH("HIGH"),

    @Json(name = "HIGHEST")
    hIGHEST("HIGHEST");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is V3TxSchedulePriority) "$data" else null

        /**
         * Returns a valid [V3TxSchedulePriority] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): V3TxSchedulePriority? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

