/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.V3UserIdentifiers

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userIds 
 * @param new 
 * @param old 
 * @param revokeAllAccess Revoke active sessions and access tokens of user if true. To be used if credentials are suspected to be compromised.
 */
@JsonClass(generateAdapter = true)
data class V3UpdateUserPasswordRequest (

    @Json(name = "user_ids")
    val userIds: V3UserIdentifiers? = null,

    @Json(name = "new")
    val new: kotlin.String? = null,

    @Json(name = "old")
    val old: kotlin.String? = null,

    /* Revoke active sessions and access tokens of user if true. To be used if credentials are suspected to be compromised. */
    @Json(name = "revoke_all_access")
    val revokeAllAccess: kotlin.Boolean? = null

)

