/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProtobufFieldMask
import org.openapitools.client.models.V3APIKey
import org.openapitools.client.models.V3OrganizationIdentifiers

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param organizationIds 
 * @param apiKey 
 * @param fieldMask 
 */
@JsonClass(generateAdapter = true)
data class V3UpdateOrganizationAPIKeyRequest (

    @Json(name = "organization_ids")
    val organizationIds: V3OrganizationIdentifiers? = null,

    @Json(name = "api_key")
    val apiKey: V3APIKey? = null,

    @Json(name = "field_mask")
    val fieldMask: ProtobufFieldMask? = null

)

