/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import org.openapitools.client.models.RuntimeError
import org.openapitools.client.models.StreamResultOfV3EndDeviceTemplate
import org.openapitools.client.models.V3ConvertEndDeviceTemplateRequest
import org.openapitools.client.models.V3EndDeviceTemplateFormats

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiInfrastructureResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class EndDeviceTemplateConverterApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
    * Converts the binary data to a stream of end device templates.
    * 
    * @param body  
    * @return StreamResultOfV3EndDeviceTemplate
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun endDeviceTemplateConverterConvert(body: V3ConvertEndDeviceTemplateRequest) : StreamResultOfV3EndDeviceTemplate {
        val localVarResponse = endDeviceTemplateConverterConvertWithHttpInfo(body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StreamResultOfV3EndDeviceTemplate
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Converts the binary data to a stream of end device templates.
    * 
    * @param body  
    * @return ApiInfrastructureResponse<StreamResultOfV3EndDeviceTemplate?>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun endDeviceTemplateConverterConvertWithHttpInfo(body: V3ConvertEndDeviceTemplateRequest) : ApiInfrastructureResponse<StreamResultOfV3EndDeviceTemplate?> {
        val localVariableConfig = endDeviceTemplateConverterConvertRequestConfig(body = body)

        return request<V3ConvertEndDeviceTemplateRequest, StreamResultOfV3EndDeviceTemplate>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation endDeviceTemplateConverterConvert
    *
    * @param body  
    * @return RequestConfig
    */
    fun endDeviceTemplateConverterConvertRequestConfig(body: V3ConvertEndDeviceTemplateRequest) : RequestConfig<V3ConvertEndDeviceTemplateRequest> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/edtc/convert",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Returns the configured formats to convert from.
    * 
    * @return V3EndDeviceTemplateFormats
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun endDeviceTemplateConverterListFormats() : V3EndDeviceTemplateFormats {
        val localVarResponse = endDeviceTemplateConverterListFormatsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V3EndDeviceTemplateFormats
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Returns the configured formats to convert from.
    * 
    * @return ApiInfrastructureResponse<V3EndDeviceTemplateFormats?>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun endDeviceTemplateConverterListFormatsWithHttpInfo() : ApiInfrastructureResponse<V3EndDeviceTemplateFormats?> {
        val localVariableConfig = endDeviceTemplateConverterListFormatsRequestConfig()

        return request<Unit, V3EndDeviceTemplateFormats>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation endDeviceTemplateConverterListFormats
    *
    * @return RequestConfig
    */
    fun endDeviceTemplateConverterListFormatsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/edtc/formats",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
