/**
 * The Things Stack for LoRaWAN v3 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import org.openapitools.client.models.RuntimeError
import org.openapitools.client.models.V3EndDevice
import org.openapitools.client.models.V3ResetAndGetEndDeviceRequest
import org.openapitools.client.models.V3SetEndDeviceRequest

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiInfrastructureResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class NsEndDeviceRegistryApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
    * Delete deletes the device that matches the given identifiers. If there are multiple matches, an error will be returned.
    * 
    * @param applicationIdsApplicationId  
    * @param deviceId  
    * @param devEui The LoRaWAN DevEUI. (optional)
    * @param joinEui The LoRaWAN JoinEUI (AppEUI until LoRaWAN 1.0.3 end devices). (optional)
    * @param devAddr The LoRaWAN DevAddr. (optional)
    * @return kotlin.Any
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistryDelete(applicationIdsApplicationId: kotlin.String, deviceId: kotlin.String, devEui: kotlin.ByteArray?, joinEui: kotlin.ByteArray?, devAddr: kotlin.ByteArray?) : kotlin.Any {
        val localVarResponse = nsEndDeviceRegistryDeleteWithHttpInfo(applicationIdsApplicationId = applicationIdsApplicationId, deviceId = deviceId, devEui = devEui, joinEui = joinEui, devAddr = devAddr)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Delete deletes the device that matches the given identifiers. If there are multiple matches, an error will be returned.
    * 
    * @param applicationIdsApplicationId  
    * @param deviceId  
    * @param devEui The LoRaWAN DevEUI. (optional)
    * @param joinEui The LoRaWAN JoinEUI (AppEUI until LoRaWAN 1.0.3 end devices). (optional)
    * @param devAddr The LoRaWAN DevAddr. (optional)
    * @return ApiInfrastructureResponse<kotlin.Any?>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistryDeleteWithHttpInfo(applicationIdsApplicationId: kotlin.String, deviceId: kotlin.String, devEui: kotlin.ByteArray?, joinEui: kotlin.ByteArray?, devAddr: kotlin.ByteArray?) : ApiInfrastructureResponse<kotlin.Any?> {
        val localVariableConfig = nsEndDeviceRegistryDeleteRequestConfig(applicationIdsApplicationId = applicationIdsApplicationId, deviceId = deviceId, devEui = devEui, joinEui = joinEui, devAddr = devAddr)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation nsEndDeviceRegistryDelete
    *
    * @param applicationIdsApplicationId  
    * @param deviceId  
    * @param devEui The LoRaWAN DevEUI. (optional)
    * @param joinEui The LoRaWAN JoinEUI (AppEUI until LoRaWAN 1.0.3 end devices). (optional)
    * @param devAddr The LoRaWAN DevAddr. (optional)
    * @return RequestConfig
    */
    fun nsEndDeviceRegistryDeleteRequestConfig(applicationIdsApplicationId: kotlin.String, deviceId: kotlin.String, devEui: kotlin.ByteArray?, joinEui: kotlin.ByteArray?, devAddr: kotlin.ByteArray?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (devEui != null) {
                    put("dev_eui", listOf(devEui.toString()))
                }
                if (joinEui != null) {
                    put("join_eui", listOf(joinEui.toString()))
                }
                if (devAddr != null) {
                    put("dev_addr", listOf(devAddr.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/ns/applications/{application_ids.application_id}/devices/{device_id}".replace("{"+"application_ids.application_id"+"}", "$applicationIdsApplicationId").replace("{"+"device_id"+"}", "$deviceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Get returns the device that matches the given identifiers. If there are multiple matches, an error will be returned.
    * 
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param endDeviceIdsDeviceId  
    * @param endDeviceIdsDevEui The LoRaWAN DevEUI. (optional)
    * @param endDeviceIdsJoinEui The LoRaWAN JoinEUI (AppEUI until LoRaWAN 1.0.3 end devices). (optional)
    * @param endDeviceIdsDevAddr The LoRaWAN DevAddr. (optional)
    * @param fieldMaskPaths The set of field mask paths. (optional)
    * @return V3EndDevice
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistryGet(endDeviceIdsApplicationIdsApplicationId: kotlin.String, endDeviceIdsDeviceId: kotlin.String, endDeviceIdsDevEui: kotlin.ByteArray?, endDeviceIdsJoinEui: kotlin.ByteArray?, endDeviceIdsDevAddr: kotlin.ByteArray?, fieldMaskPaths: kotlin.collections.List<kotlin.String>?) : V3EndDevice {
        val localVarResponse = nsEndDeviceRegistryGetWithHttpInfo(endDeviceIdsApplicationIdsApplicationId = endDeviceIdsApplicationIdsApplicationId, endDeviceIdsDeviceId = endDeviceIdsDeviceId, endDeviceIdsDevEui = endDeviceIdsDevEui, endDeviceIdsJoinEui = endDeviceIdsJoinEui, endDeviceIdsDevAddr = endDeviceIdsDevAddr, fieldMaskPaths = fieldMaskPaths)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V3EndDevice
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Get returns the device that matches the given identifiers. If there are multiple matches, an error will be returned.
    * 
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param endDeviceIdsDeviceId  
    * @param endDeviceIdsDevEui The LoRaWAN DevEUI. (optional)
    * @param endDeviceIdsJoinEui The LoRaWAN JoinEUI (AppEUI until LoRaWAN 1.0.3 end devices). (optional)
    * @param endDeviceIdsDevAddr The LoRaWAN DevAddr. (optional)
    * @param fieldMaskPaths The set of field mask paths. (optional)
    * @return ApiInfrastructureResponse<V3EndDevice?>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistryGetWithHttpInfo(endDeviceIdsApplicationIdsApplicationId: kotlin.String, endDeviceIdsDeviceId: kotlin.String, endDeviceIdsDevEui: kotlin.ByteArray?, endDeviceIdsJoinEui: kotlin.ByteArray?, endDeviceIdsDevAddr: kotlin.ByteArray?, fieldMaskPaths: kotlin.collections.List<kotlin.String>?) : ApiInfrastructureResponse<V3EndDevice?> {
        val localVariableConfig = nsEndDeviceRegistryGetRequestConfig(endDeviceIdsApplicationIdsApplicationId = endDeviceIdsApplicationIdsApplicationId, endDeviceIdsDeviceId = endDeviceIdsDeviceId, endDeviceIdsDevEui = endDeviceIdsDevEui, endDeviceIdsJoinEui = endDeviceIdsJoinEui, endDeviceIdsDevAddr = endDeviceIdsDevAddr, fieldMaskPaths = fieldMaskPaths)

        return request<Unit, V3EndDevice>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation nsEndDeviceRegistryGet
    *
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param endDeviceIdsDeviceId  
    * @param endDeviceIdsDevEui The LoRaWAN DevEUI. (optional)
    * @param endDeviceIdsJoinEui The LoRaWAN JoinEUI (AppEUI until LoRaWAN 1.0.3 end devices). (optional)
    * @param endDeviceIdsDevAddr The LoRaWAN DevAddr. (optional)
    * @param fieldMaskPaths The set of field mask paths. (optional)
    * @return RequestConfig
    */
    fun nsEndDeviceRegistryGetRequestConfig(endDeviceIdsApplicationIdsApplicationId: kotlin.String, endDeviceIdsDeviceId: kotlin.String, endDeviceIdsDevEui: kotlin.ByteArray?, endDeviceIdsJoinEui: kotlin.ByteArray?, endDeviceIdsDevAddr: kotlin.ByteArray?, fieldMaskPaths: kotlin.collections.List<kotlin.String>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (endDeviceIdsDevEui != null) {
                    put("end_device_ids.dev_eui", listOf(endDeviceIdsDevEui.toString()))
                }
                if (endDeviceIdsJoinEui != null) {
                    put("end_device_ids.join_eui", listOf(endDeviceIdsJoinEui.toString()))
                }
                if (endDeviceIdsDevAddr != null) {
                    put("end_device_ids.dev_addr", listOf(endDeviceIdsDevAddr.toString()))
                }
                if (fieldMaskPaths != null) {
                    put("field_mask.paths", toMultiValue(fieldMaskPaths.toList(), "multi"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/ns/applications/{end_device_ids.application_ids.application_id}/devices/{end_device_ids.device_id}".replace("{"+"end_device_ids.application_ids.application_id"+"}", "$endDeviceIdsApplicationIdsApplicationId").replace("{"+"end_device_ids.device_id"+"}", "$endDeviceIdsDeviceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * ResetFactoryDefaults resets device state to factory defaults.
    * 
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param endDeviceIdsDeviceId  
    * @param body  
    * @return V3EndDevice
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistryResetFactoryDefaults(endDeviceIdsApplicationIdsApplicationId: kotlin.String, endDeviceIdsDeviceId: kotlin.String, body: V3ResetAndGetEndDeviceRequest) : V3EndDevice {
        val localVarResponse = nsEndDeviceRegistryResetFactoryDefaultsWithHttpInfo(endDeviceIdsApplicationIdsApplicationId = endDeviceIdsApplicationIdsApplicationId, endDeviceIdsDeviceId = endDeviceIdsDeviceId, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V3EndDevice
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * ResetFactoryDefaults resets device state to factory defaults.
    * 
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param endDeviceIdsDeviceId  
    * @param body  
    * @return ApiInfrastructureResponse<V3EndDevice?>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistryResetFactoryDefaultsWithHttpInfo(endDeviceIdsApplicationIdsApplicationId: kotlin.String, endDeviceIdsDeviceId: kotlin.String, body: V3ResetAndGetEndDeviceRequest) : ApiInfrastructureResponse<V3EndDevice?> {
        val localVariableConfig = nsEndDeviceRegistryResetFactoryDefaultsRequestConfig(endDeviceIdsApplicationIdsApplicationId = endDeviceIdsApplicationIdsApplicationId, endDeviceIdsDeviceId = endDeviceIdsDeviceId, body = body)

        return request<V3ResetAndGetEndDeviceRequest, V3EndDevice>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation nsEndDeviceRegistryResetFactoryDefaults
    *
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param endDeviceIdsDeviceId  
    * @param body  
    * @return RequestConfig
    */
    fun nsEndDeviceRegistryResetFactoryDefaultsRequestConfig(endDeviceIdsApplicationIdsApplicationId: kotlin.String, endDeviceIdsDeviceId: kotlin.String, body: V3ResetAndGetEndDeviceRequest) : RequestConfig<V3ResetAndGetEndDeviceRequest> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/ns/applications/{end_device_ids.application_ids.application_id}/devices/{end_device_ids.device_id}".replace("{"+"end_device_ids.application_ids.application_id"+"}", "$endDeviceIdsApplicationIdsApplicationId").replace("{"+"end_device_ids.device_id"+"}", "$endDeviceIdsDeviceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Set creates or updates the device.
    * 
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param endDeviceIdsDeviceId  
    * @param body  
    * @return V3EndDevice
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistrySet(endDeviceIdsApplicationIdsApplicationId: kotlin.String, endDeviceIdsDeviceId: kotlin.String, body: V3SetEndDeviceRequest) : V3EndDevice {
        val localVarResponse = nsEndDeviceRegistrySetWithHttpInfo(endDeviceIdsApplicationIdsApplicationId = endDeviceIdsApplicationIdsApplicationId, endDeviceIdsDeviceId = endDeviceIdsDeviceId, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V3EndDevice
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Set creates or updates the device.
    * 
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param endDeviceIdsDeviceId  
    * @param body  
    * @return ApiInfrastructureResponse<V3EndDevice?>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistrySetWithHttpInfo(endDeviceIdsApplicationIdsApplicationId: kotlin.String, endDeviceIdsDeviceId: kotlin.String, body: V3SetEndDeviceRequest) : ApiInfrastructureResponse<V3EndDevice?> {
        val localVariableConfig = nsEndDeviceRegistrySetRequestConfig(endDeviceIdsApplicationIdsApplicationId = endDeviceIdsApplicationIdsApplicationId, endDeviceIdsDeviceId = endDeviceIdsDeviceId, body = body)

        return request<V3SetEndDeviceRequest, V3EndDevice>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation nsEndDeviceRegistrySet
    *
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param endDeviceIdsDeviceId  
    * @param body  
    * @return RequestConfig
    */
    fun nsEndDeviceRegistrySetRequestConfig(endDeviceIdsApplicationIdsApplicationId: kotlin.String, endDeviceIdsDeviceId: kotlin.String, body: V3SetEndDeviceRequest) : RequestConfig<V3SetEndDeviceRequest> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/ns/applications/{end_device.ids.application_ids.application_id}/devices/{end_device.ids.device_id}".replace("{"+"end_device.ids.application_ids.application_id"+"}", "$endDeviceIdsApplicationIdsApplicationId").replace("{"+"end_device.ids.device_id"+"}", "$endDeviceIdsDeviceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Set creates or updates the device.
    * 
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param body  
    * @return V3EndDevice
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistrySet2(endDeviceIdsApplicationIdsApplicationId: kotlin.String, body: V3SetEndDeviceRequest) : V3EndDevice {
        val localVarResponse = nsEndDeviceRegistrySet2WithHttpInfo(endDeviceIdsApplicationIdsApplicationId = endDeviceIdsApplicationIdsApplicationId, body = body)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V3EndDevice
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Set creates or updates the device.
    * 
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param body  
    * @return ApiInfrastructureResponse<V3EndDevice?>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun nsEndDeviceRegistrySet2WithHttpInfo(endDeviceIdsApplicationIdsApplicationId: kotlin.String, body: V3SetEndDeviceRequest) : ApiInfrastructureResponse<V3EndDevice?> {
        val localVariableConfig = nsEndDeviceRegistrySet2RequestConfig(endDeviceIdsApplicationIdsApplicationId = endDeviceIdsApplicationIdsApplicationId, body = body)

        return request<V3SetEndDeviceRequest, V3EndDevice>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation nsEndDeviceRegistrySet2
    *
    * @param endDeviceIdsApplicationIdsApplicationId  
    * @param body  
    * @return RequestConfig
    */
    fun nsEndDeviceRegistrySet2RequestConfig(endDeviceIdsApplicationIdsApplicationId: kotlin.String, body: V3SetEndDeviceRequest) : RequestConfig<V3SetEndDeviceRequest> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/ns/applications/{end_device.ids.application_ids.application_id}/devices".replace("{"+"end_device.ids.application_ids.application_id"+"}", "$endDeviceIdsApplicationIdsApplicationId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
