/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param createApplications 
 * @param createClients 
 * @param createGateways 
 * @param createOrganizations 
 */

data class IsConfigurationUserRights (
    @Json(name = "create_applications")
    val createApplications: kotlin.Boolean? = null,
    @Json(name = "create_clients")
    val createClients: kotlin.Boolean? = null,
    @Json(name = "create_gateways")
    val createGateways: kotlin.Boolean? = null,
    @Json(name = "create_organizations")
    val createOrganizations: kotlin.Boolean? = null
)

