/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param margin Indicates the link margin in dB of the received LinkCheckReq, relative to the demodulation floor.
 * @param gatewayCount 
 */

data class MACCommandLinkCheckAns (
    /* Indicates the link margin in dB of the received LinkCheckReq, relative to the demodulation floor. */
    @Json(name = "margin")
    val margin: kotlin.Long? = null,
    @Json(name = "gateway_count")
    val gatewayCount: kotlin.Long? = null
)

