/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param battery Device battery status. 0 indicates that the device is connected to an external power source. 1..254 indicates a battery level. 255 indicates that the device was not able to measure the battery level.
 * @param margin SNR of the last downlink (dB; [-32, +31]).
 */

data class MACCommandDevStatusAns (
    /* Device battery status. 0 indicates that the device is connected to an external power source. 1..254 indicates a battery level. 255 indicates that the device was not able to measure the battery level. */
    @Json(name = "battery")
    val battery: kotlin.Long? = null,
    /* SNR of the last downlink (dB; [-32, +31]). */
    @Json(name = "margin")
    val margin: kotlin.Int? = null
)

