/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.V3DataRateIndex
import org.openapitools.client.models.V3RejoinPeriodExponent
import org.openapitools.client.models.V3RejoinType

import com.squareup.moshi.Json

/**
 * 
 * @param rejoinType 
 * @param dataRateIndex 
 * @param maxRetries 
 * @param periodExponent 
 */

data class MACCommandForceRejoinReq (
    @Json(name = "rejoin_type")
    val rejoinType: V3RejoinType? = null,
    @Json(name = "data_rate_index")
    val dataRateIndex: V3DataRateIndex? = null,
    @Json(name = "max_retries")
    val maxRetries: kotlin.Long? = null,
    @Json(name = "period_exponent")
    val periodExponent: V3RejoinPeriodExponent? = null
)

