/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param rx2DataRateIndexAck 
 * @param rx1DataRateOffsetAck 
 * @param rx2FrequencyAck 
 */

data class MACCommandRxParamSetupAns (
    @Json(name = "rx2_data_rate_index_ack")
    val rx2DataRateIndexAck: kotlin.Boolean? = null,
    @Json(name = "rx1_data_rate_offset_ack")
    val rx1DataRateOffsetAck: kotlin.Boolean? = null,
    @Json(name = "rx2_frequency_ack")
    val rx2FrequencyAck: kotlin.Boolean? = null
)

