/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.RuntimeStreamError
import org.openapitools.client.models.V3Event

import com.squareup.moshi.Json

/**
 * 
 * @param result 
 * @param error 
 */

data class StreamResultOfV3Event (
    @Json(name = "result")
    val result: V3Event? = null,
    @Json(name = "error")
    val error: RuntimeStreamError? = null
)

