/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.V3AggregatedDutyCycle

import com.squareup.moshi.Json

/**
 * 
 * @param value 
 */

data class V3AggregatedDutyCycleValue (
    @Json(name = "value")
    val value: V3AggregatedDutyCycle? = null
)

