/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param path Path to append to the base URL. Can contain template fields, in RFC 6570 format.
 */

data class V3ApplicationWebhookTemplateMessage (
    /* Path to append to the base URL. Can contain template fields, in RFC 6570 format. */
    @Json(name = "path")
    val path: kotlin.String? = null
)

