/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param name 
 * @param defaultFPort 
 */

data class V3ApplicationPackage (
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "default_f_port")
    val defaultFPort: kotlin.Long? = null
)

