/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.V3ContactMethod
import org.openapitools.client.models.V3ContactType

import com.squareup.moshi.Json

/**
 * 
 * @param contactType 
 * @param contactMethod 
 * @param value 
 * @param public 
 * @param validatedAt 
 */

data class V3ContactInfo (
    @Json(name = "contact_type")
    val contactType: V3ContactType? = null,
    @Json(name = "contact_method")
    val contactMethod: V3ContactMethod? = null,
    @Json(name = "value")
    val value: kotlin.String? = null,
    @Json(name = "public")
    val public: kotlin.Boolean? = null,
    @Json(name = "validated_at")
    val validatedAt: java.time.OffsetDateTime? = null
)

