/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.V3DataRateIndex

import com.squareup.moshi.Json

/**
 * 
 * @param rx1DrOffset 
 * @param rx2Dr 
 * @param optNeg OptNeg is set if Network Server implements LoRaWAN 1.1 or greater.
 */

data class V3DLSettings (
    @Json(name = "rx1_dr_offset")
    val rx1DrOffset: kotlin.Long? = null,
    @Json(name = "rx2_dr")
    val rx2Dr: V3DataRateIndex? = null,
    /* OptNeg is set if Network Server implements LoRaWAN 1.1 or greater. */
    @Json(name = "opt_neg")
    val optNeg: kotlin.Boolean? = null
)

