/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Lorawanv3Message
import org.openapitools.client.models.V3CFList
import org.openapitools.client.models.V3DLSettings
import org.openapitools.client.models.V3MACVersion
import org.openapitools.client.models.V3RxDelay

import com.squareup.moshi.Json

/**
 * 
 * @param rawPayload 
 * @param payload 
 * @param devAddr 
 * @param selectedMacVersion 
 * @param netId 
 * @param downlinkSettings 
 * @param rxDelay 
 * @param cfList 
 * @param correlationIds 
 * @param consumedAirtime Consumed airtime for the transmission of the join request. Calculated by Network Server using the RawPayload size and the transmission settings.
 */

data class V3JoinRequest (
    @Json(name = "raw_payload")
    val rawPayload: kotlin.ByteArray? = null,
    @Json(name = "payload")
    val payload: Lorawanv3Message? = null,
    @Json(name = "dev_addr")
    val devAddr: kotlin.ByteArray? = null,
    @Json(name = "selected_mac_version")
    val selectedMacVersion: V3MACVersion? = null,
    @Json(name = "net_id")
    val netId: kotlin.ByteArray? = null,
    @Json(name = "downlink_settings")
    val downlinkSettings: V3DLSettings? = null,
    @Json(name = "rx_delay")
    val rxDelay: V3RxDelay? = null,
    @Json(name = "cf_list")
    val cfList: V3CFList? = null,
    @Json(name = "correlation_ids")
    val correlationIds: kotlin.collections.List<kotlin.String>? = null,
    /* Consumed airtime for the transmission of the join request. Calculated by Network Server using the RawPayload size and the transmission settings. */
    @Json(name = "consumed_airtime")
    val consumedAirtime: kotlin.String? = null
)

