/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.V3OrganizationIdentifiers
import org.openapitools.client.models.V3UserIdentifiers

import com.squareup.moshi.Json

/**
 * OrganizationOrUserIdentifiers contains either organization or user identifiers.
 * @param organizationIds 
 * @param userIds 
 */

data class V3OrganizationOrUserIdentifiers (
    @Json(name = "organization_ids")
    val organizationIds: V3OrganizationIdentifiers? = null,
    @Json(name = "user_ids")
    val userIds: V3UserIdentifiers? = null
)

