/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* 
* Values: _1s,_2s,_4s,_8s,_16s,_32s,_64s,_128s
*/

enum class V3PingSlotPeriod(val value: kotlin.String){


    @Json(name = "PING_EVERY_1S")
    _1s("PING_EVERY_1S"),


    @Json(name = "PING_EVERY_2S")
    _2s("PING_EVERY_2S"),


    @Json(name = "PING_EVERY_4S")
    _4s("PING_EVERY_4S"),


    @Json(name = "PING_EVERY_8S")
    _8s("PING_EVERY_8S"),


    @Json(name = "PING_EVERY_16S")
    _16s("PING_EVERY_16S"),


    @Json(name = "PING_EVERY_32S")
    _32s("PING_EVERY_32S"),


    @Json(name = "PING_EVERY_64S")
    _64s("PING_EVERY_64S"),


    @Json(name = "PING_EVERY_128S")
    _128s("PING_EVERY_128S");



    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }

}

