/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.V3KeyEnvelope

import com.squareup.moshi.Json

/**
 * Root keys for a LoRaWAN device. These are stored on the Join Server.
 * @param rootKeyId Join Server issued identifier for the root keys.
 * @param appKey 
 * @param nwkKey 
 */

data class V3RootKeys (
    /* Join Server issued identifier for the root keys. */
    @Json(name = "root_key_id")
    val rootKeyId: kotlin.String? = null,
    @Json(name = "app_key")
    val appKey: V3KeyEnvelope? = null,
    @Json(name = "nwk_key")
    val nwkKey: V3KeyEnvelope? = null
)

