/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.V3EntityIdentifiers

import com.squareup.moshi.Json

/**
 * 
 * @param identifiers 
 * @param tail If greater than zero, this will return historical events, up to this maximum when the stream starts. If used in combination with \"after\", the limit that is reached first, is used. The availability of historical events depends on server support and retention policy.
 * @param after If not empty, this will return historical events after the given time when the stream starts. If used in combination with \"tail\", the limit that is reached first, is used. The availability of historical events depends on server support and retention policy.
 */

data class V3StreamEventsRequest (
    @Json(name = "identifiers")
    val identifiers: kotlin.collections.List<V3EntityIdentifiers>? = null,
    /* If greater than zero, this will return historical events, up to this maximum when the stream starts. If used in combination with \"after\", the limit that is reached first, is used. The availability of historical events depends on server support and retention policy. */
    @Json(name = "tail")
    val tail: kotlin.Long? = null,
    /* If not empty, this will return historical events after the given time when the stream starts. If used in combination with \"tail\", the limit that is reached first, is used. The availability of historical events depends on server support and retention policy. */
    @Json(name = "after")
    val after: java.time.OffsetDateTime? = null
)

