/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ProtobufFieldMask
import org.openapitools.client.models.V3User

import com.squareup.moshi.Json

/**
 * 
 * @param user 
 * @param fieldMask 
 */

data class V3UpdateUserRequest (
    @Json(name = "user")
    val user: V3User? = null,
    @Json(name = "field_mask")
    val fieldMask: ProtobufFieldMask? = null
)

