/**
* The Things Stack for LoRaWAN v3 API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Lorawanv3Message
import org.openapitools.client.models.V3RxMetadata
import org.openapitools.client.models.V3TxSettings

import com.squareup.moshi.Json

/**
 * 
 * @param rawPayload 
 * @param payload 
 * @param settings 
 * @param rxMetadata 
 * @param receivedAt Server time when a component received the message. The Gateway Server and Network Server set this value to their local server time of reception.
 * @param correlationIds 
 * @param deviceChannelIndex Index of the device channel that received the message. Set by Network Server.
 * @param consumedAirtime Consumed airtime for the transmission of the uplink message. Calculated by Network Server using the RawPayload size and the transmission settings.
 */

data class V3UplinkMessage (
    @Json(name = "raw_payload")
    val rawPayload: kotlin.ByteArray? = null,
    @Json(name = "payload")
    val payload: Lorawanv3Message? = null,
    @Json(name = "settings")
    val settings: V3TxSettings? = null,
    @Json(name = "rx_metadata")
    val rxMetadata: kotlin.collections.List<V3RxMetadata>? = null,
    /* Server time when a component received the message. The Gateway Server and Network Server set this value to their local server time of reception. */
    @Json(name = "received_at")
    val receivedAt: java.time.OffsetDateTime? = null,
    @Json(name = "correlation_ids")
    val correlationIds: kotlin.collections.List<kotlin.String>? = null,
    /* Index of the device channel that received the message. Set by Network Server. */
    @Json(name = "device_channel_index")
    val deviceChannelIndex: kotlin.Long? = null,
    /* Consumed airtime for the transmission of the uplink message. Calculated by Network Server using the RawPayload size and the transmission settings. */
    @Json(name = "consumed_airtime")
    val consumedAirtime: kotlin.String? = null
)

